# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '180703.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(643, 441)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 20, 281, 301))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/haha.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.lcdNumber_2 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(500, 100, 111, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setFrameShape(QtGui.QFrame.Panel)
        self.lcdNumber_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_2.setLineWidth(10000)
        self.lcdNumber_2.setSmallDecimalPoint(True)
        self.lcdNumber_2.setProperty("value", 90.0)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.horizontalSlider = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(140, 340, 321, 51))
        self.horizontalSlider.setStyleSheet(_fromUtf8("background: cyan;"))
        self.horizontalSlider.setMinimum(4000)
        self.horizontalSlider.setMaximum(11000)
        self.horizontalSlider.setProperty("value", 8000)
        self.horizontalSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.verticalSlider = QtGui.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(110, 20, 61, 311))
        self.verticalSlider.setStyleSheet(_fromUtf8("background: cyan;"))
        self.verticalSlider.setMinimum(4000)
        self.verticalSlider.setMaximum(11000)
        self.verticalSlider.setProperty("value", 8000)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 111, 281))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/chart.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lcdNumber_3 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(10, 340, 111, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcdNumber_3.setFont(font)
        self.lcdNumber_3.setFrameShape(QtGui.QFrame.Panel)
        self.lcdNumber_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_3.setLineWidth(10000)
        self.lcdNumber_3.setSmallDecimalPoint(True)
        self.lcdNumber_3.setProperty("value", 90.0)
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(490, 220, 121, 161))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/chart.png")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 70, 70, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 290, 100, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(510, 140, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(520, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lcdNumber_4 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setGeometry(QtCore.QRect(479, 30, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcdNumber_4.setFont(font)
        self.lcdNumber_4.setFrameShape(QtGui.QFrame.Panel)
        self.lcdNumber_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_4.setLineWidth(10000)
        self.lcdNumber_4.setSmallDecimalPoint(False)
        self.lcdNumber_4.setProperty("value", 90.0)
        self.lcdNumber_4.setObjectName(_fromUtf8("lcdNumber_4"))
#        self.lcdNumber_4.setStyleSheet(_fromUtf8("background: cyan;"))        
        self.lcdNumber_5 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_5.setGeometry(QtCore.QRect(540, 30, 71, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcdNumber_5.setFont(font)
        self.lcdNumber_5.setFrameShape(QtGui.QFrame.Panel)
        self.lcdNumber_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_5.setLineWidth(10000)
        self.lcdNumber_5.setSmallDecimalPoint(False)
        self.lcdNumber_5.setProperty("value", 90.0)
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(558, 35, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lcdNumber_2.raise_()
        self.horizontalSlider.raise_()
        self.verticalSlider.raise_()
        self.label_2.raise_()
        self.lcdNumber_3.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.lcdNumber_5.raise_()
        self.lcdNumber_4.raise_()
        self.label.raise_()
        self.label_8.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 643, 17))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(170, 180, 30, 30))
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_8"))
        self.label_9.setText(_translate("MainWindow", "Ｎ", None))
        self.label_9.raise_()

#        510, 150, 110, 31))
        self.lcdNumber_6 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_6.setGeometry(QtCore.QRect(500, 180, 111, 41))
        self.lcdNumber_6.setFont(font)
        self.lcdNumber_6.setFrameShape(QtGui.QFrame.Panel)
        self.lcdNumber_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_6.setLineWidth(10000)
        self.lcdNumber_6.setSmallDecimalPoint(True)
        self.lcdNumber_6.setProperty("value", 90.0)
        self.lcdNumber_6.setObjectName(_fromUtf8("lcdNumber_2"))
        
    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_4.setText(_translate("MainWindow", "RPM", None))
        self.label_5.setText(_translate("MainWindow", "高度(m)", None))
        self.label_6.setText(_translate("MainWindow", "対気速度", None))
        self.label_7.setText(_translate("MainWindow", "時間", None))
        self.label_8.setText(_translate("MainWindow", "：", None))



